import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import Menu from './components/menu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Awwards',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Menu />
      </body>
    </html>
  )
}
