import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import './globals.scss'
import Menu from './components/menu'
import Header from './components/header'

const inter = Lato({
  weight: ['100','300', '400', '700', '900'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Awwards',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Menu />
      </body>
    </html>
  )
}
